language: objective-c
osx_image: xcode7.3

script:
- set -o pipefail && xctool test -workspace Example/SnowFallViewExample.xcworkspace -scheme SnowFallViewExample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- pod lib lint
